# Generated by Django 5.2.10 on 2026-02-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
