# Generated by Django 5.2.11 on 2026-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='debito_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
