# Generated by Django 6.0.1 on 2026-01-08 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('finance', '0002_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('FIADO', 'Fiado')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments_quantity', models.PositiveSmallIntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('concluded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cards.card')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
