# Generated by Django 6.0 on 2026-01-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_last_four_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_four_digits',
            field=models.CharField(max_length=4),
        ),
    ]
