# Generated by Django 6.0 on 2026-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_last_four_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiration_month',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_year',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
