# Generated by Django 6.0 on 2026-01-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_expiration_month_card_expiration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
